# -*- coding: utf-8 -*-
"""ey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17HE7L2xa7A95tL3dIBtqprreMUAKE0sr
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('NEV_fault_dataset new.csv')
df.head()

df.shape          # shows number of rows & columns
df.columns        # lists all column names
df.info()         # shows column data types & missing values
df.describe()     # quick numeric summary

df = df.drop_duplicates()
df = df.fillna(df.mean(numeric_only=True))

df.columns

plt.hist(df['Temperature (°C)'], bins=20)

import numpy as np

synthetic = df.sample(10, replace=True).copy()
synthetic['Vehicle_ID'] = [f'VEH_{i:03d}' for i in range(1, 11)]
synthetic.head()

cols_to_fix = ['Voltage (V)', 'Current (A)', 'Motor Speed (RPM)',
               'Temperature (°C)', 'Vibration (g)', 'Ambient Temp (°C)', 'Humidity (%)']

for col in cols_to_fix:
    synthetic[col] = (
        synthetic[col]
        .astype(str)                              # make sure it's string
        .str.replace(r'[^0-9]', '', regex=True)   # remove ALL non-digit characters (like . or ,)
        .astype(float)                            # convert to float
    )

synthetic['Voltage (V)'] = synthetic['Voltage (V)'] / 1000000
synthetic['Current (A)'] = synthetic['Current (A)'] / 1000000
synthetic['Temperature (°C)'] = synthetic['Temperature (°C)'] / 1000000
synthetic['Vibration (g)'] = synthetic['Vibration (g)'] / 1000000
synthetic['Ambient Temp (°C)'] = synthetic['Ambient Temp (°C)'] / 1000000
synthetic['Humidity (%)'] = synthetic['Humidity (%)'] / 1000000

synthetic[cols_to_fix].head()

# Scale down unrealistic values
synthetic['Voltage (V)'] = synthetic['Voltage (V)'] / 1e7
synthetic['Current (A)'] = synthetic['Current (A)'] / 1e8
synthetic['Motor Speed (RPM)'] = synthetic['Motor Speed (RPM)'] / 1e12
synthetic['Temperature (°C)'] = synthetic['Temperature (°C)'] / 1e9
synthetic['Vibration (g)'] = synthetic['Vibration (g)'] / 1e9
synthetic['Ambient Temp (°C)'] = synthetic['Ambient Temp (°C)'] / 1e9
synthetic['Humidity (%)'] = synthetic['Humidity (%)'] / 1e9

synthetic.head()

synthetic.describe()

def predictive_maintenance(row):
    issues = []
    if row['Voltage (V)'] < 200 or row['Voltage (V)'] > 900:
        issues.append('Abnormal voltage')
    if row['Current (A)'] > 300:
        issues.append('Motor overload')
    if row['Temperature (°C)'] > 70:
        issues.append('Overheating risk')
    if row['Vibration (g)'] > 10:
        issues.append('High vibration - mechanical issue')
    if row['Ambient Temp (°C)'] > 45:
        issues.append('External heat stress')
    if row['Humidity (%)'] > 80:
        issues.append('Moisture exposure risk')

    return 'Healthy' if len(issues) == 0 else ', '.join(issues)

synthetic['Predicted_Fault'] = synthetic.apply(predictive_maintenance, axis=1)
synthetic[['Vehicle_ID', 'Predicted_Fault']].head(10)

import matplotlib.pyplot as plt

# Count each fault type
fault_counts = synthetic['Predicted_Fault'].value_counts()

plt.figure(figsize=(10,6))
plt.barh(fault_counts.index, fault_counts.values)
plt.xlabel('Number of Vehicles')
plt.ylabel('Predicted Fault Type')
plt.title('Predictive Maintenance – Fault Type Distribution')
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.show()

plt.barh(fault_counts.index, fault_counts.values, color=['#ff9999','#66b3ff','#99ff99','#ffcc99','#c2c2f0'])

def fault_severity(fault):
    if fault == 'Healthy':
        return 'Low'
    elif 'Overheating' in fault or 'Motor overload' in fault:
        return 'Critical'
    else:
        return 'Moderate'

synthetic['Severity'] = synthetic['Predicted_Fault'].apply(fault_severity)
synthetic[['Vehicle_ID', 'Predicted_Fault', 'Severity']].head(10)

!ls -la

from google.colab import files
uploaded = files.upload()   # choose NEV_fault_dataset new.csv
import pandas as pd
df = pd.read_csv('NEV_fault_dataset new.csv')
df.head()

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# If you've just uploaded via files.upload(), copy it to Drive:
!cp "NEV_fault_dataset new.csv" /content/drive/MyDrive/

# Or if it's already in your Drive in a folder, load directly:
df = pd.read_csv('/content/drive/MyDrive/NEV_fault_dataset new.csv')
df.head()

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!ls /content/drive/MyDrive/ColabDatasets

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!ls /content/drive/MyDrive/

!mkdir -p /content/drive/MyDrive/ColabDatasets

!ls /content/drive/MyDrive/ColabDatasets

!ls /content/drive/MyDrive/ColabDatasets

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/ColabDatasets/NEV_fault_dataset new.csv')
df.head()

import numpy as np
import pandas as pd

# Create synthetic dataset (10 random samples)
synthetic = df.sample(10, replace=True).copy()

# Add vehicle IDs
synthetic['Vehicle_ID'] = [f'VEH_{i:03d}' for i in range(1, 11)]

synthetic.head()

# Add new simulated fault-related columns
synthetic['Tire_Pressure (psi)'] = np.random.uniform(25, 40, len(synthetic))
synthetic['Oil_Level (%)'] = np.random.uniform(20, 100, len(synthetic))
synthetic['Chain_Wear (%)'] = np.random.uniform(10, 90, len(synthetic))
synthetic['Brake_Efficiency (%)'] = np.random.uniform(60, 100, len(synthetic))
synthetic['Suspension_Health (%)'] = np.random.uniform(70, 100, len(synthetic))

synthetic.head()

import re

cols_to_fix = ['Voltage (V)', 'Current (A)', 'Motor Speed (RPM)',
               'Temperature (°C)', 'Vibration (g)', 'Ambient Temp (°C)', 'Humidity (%)']

def clean_number(val):
    val = str(val)
    # Remove all characters except digits, minus sign, and dots
    val = re.sub(r'[^0-9.-]', '', val)
    # If more than one dot exists, remove all except the last one
    if val.count('.') > 1:
        parts = val.split('.')
        val = ''.join(parts[:-1]) + '.' + parts[-1]
    try:
        return float(val)
    except:
        return np.nan  # handle bad values gracefully

for col in cols_to_fix:
    synthetic[col] = synthetic[col].apply(clean_number)

synthetic[cols_to_fix].head()

# Define desired realistic ranges
scaling_factors = {
    'Voltage (V)': 1e-6,       # reduce from billions to 0–600V
    'Current (A)': 1e-8,       # reduce to ~0–300A
    'Motor Speed (RPM)': 1e-10, # reduce to ~0–8000 RPM
    'Temperature (°C)': 1e-8,   # reduce to 20–120°C
    'Vibration (g)': 1e-9,     # reduce to 0–20g
    'Ambient Temp (°C)': 1e-8,  # reduce to 20–45°C
    'Humidity (%)': 1e-9        # reduce to 20–100%
}

for col, factor in scaling_factors.items():
    synthetic[col] = synthetic[col] * factor

synthetic[cols_to_fix].head()

synthetic.describe()

# Define scaling factors to bring values to realistic ranges
scaling_factors = {
    'Voltage (V)': 1e-6,        # 8e6 → ~8 V realistic for low voltage EV battery sample
    'Current (A)': 1e-5,        # 1e6 → 10 A
    'Motor Speed (RPM)': 1e-3,  # 1000x reduction to 100–8000 RPM
    'Temperature (°C)': 1e-4,   # scale to 20–120°C range
    'Vibration (g)': 1e-4,      # scale to 0–20g range
    'Ambient Temp (°C)': 1e-4,  # 20–45°C
    'Humidity (%)': 1e-4        # 20–100%
}

for col, factor in scaling_factors.items():
    synthetic[col] = synthetic[col] * factor

synthetic.describe()

synthetic.describe()

def predictive_maintenance(row):
    issues = []

    # Electrical / Power faults
    if row['Voltage (V)'] < 11 or row['Voltage (V)'] > 600:
        issues.append('Battery or internal circuit fault')
    if row['Current (A)'] > 250:
        issues.append('Motor overload')

    # Thermal issues
    if row['Temperature (°C)'] > 90:
        issues.append('Engine overheating / oil temperature high')

    # Tyre pressure
    if row['Tire_Pressure (psi)'] < 30:
        issues.append('Low tyre pressure')

    # Oil levels
    if row['Oil_Level (%)'] < 30:
        issues.append('Low oil level')

    # Chain / mechanical imbalance
    if row['Vibration (g)'] > 10:
        issues.append('Mechanical imbalance / chain or clutch issue')

    # Brakes
    if row['Brake_Efficiency (%)'] < 75:
        issues.append('Brake wear / needs inspection')

    # Suspension
    if row['Suspension_Health (%)'] < 80:
        issues.append('Suspension issue')

    return 'Healthy' if not issues else ', '.join(issues)

synthetic['Predicted_Fault'] = synthetic.apply(predictive_maintenance, axis=1)
synthetic[['Vehicle_ID', 'Predicted_Fault']]

import matplotlib.pyplot as plt

# Count how many faults each vehicle has
fault_counts = synthetic['Predicted_Fault'].apply(
    lambda x: 0 if x == 'Healthy' else len(x.split(','))
)

plt.figure(figsize=(10,6))
plt.bar(synthetic['Vehicle_ID'], fault_counts, color='skyblue')
plt.title('Number of Detected Faults per Vehicle', fontsize=14)
plt.xlabel('Vehicle ID')
plt.ylabel('Fault Count')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(6,6))
synthetic['Predicted_Fault'].apply(
    lambda x: 'Healthy' if x == 'Healthy' else 'Faulty'
).value_counts().plot.pie(autopct='%1.1f%%', startangle=90, colors=['lightgreen', 'salmon'])
plt.title('Overall Vehicle Health Distribution', fontsize=14)
plt.ylabel('')
plt.show()

from collections import Counter

# Flatten all fault descriptions into a single list
all_faults = []
for issues in synthetic['Predicted_Fault']:
    if issues != 'Healthy':
        all_faults.extend([i.strip() for i in issues.split(',')])

fault_summary = pd.DataFrame(Counter(all_faults).items(), columns=['Fault Type', 'Count'])
fault_summary = fault_summary.sort_values(by='Count', ascending=False)

plt.figure(figsize=(8,5))
plt.barh(fault_summary['Fault Type'], fault_summary['Count'], color='orange')
plt.title('Most Common Fault Types Detected', fontsize=14)
plt.xlabel('Frequency')
plt.gca().invert_yaxis()
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

fault_summary

def predictive_maintenance(row):
    issues = []

    # 1️⃣ Battery or Circuit Faults
    if (row['Voltage (V)'] < 11.5 or row['Voltage (V)'] > 450):
        issues.append('Battery or circuit fault')

    # 2️⃣ Motor Overload
    if row['Current (A)'] > 250:
        issues.append('Motor overload detected')

    # 3️⃣ Engine / Oil Overheating
    if row['Temperature (°C)'] > 100:
        issues.append('Engine or motor overheating')

    # 4️⃣ Tyre Pressure
    if row['Tire_Pressure (psi)'] < 30:
        issues.append('Low tyre pressure')

    # 5️⃣ Oil Level
    if row['Oil_Level (%)'] < 40:
        issues.append('Low oil level')

    # 6️⃣ Chain / Clutch Imbalance
    if row['Vibration (g)'] > 7:
        issues.append('Mechanical imbalance (chain/clutch)')

    # 7️⃣ Brake Efficiency
    if row['Brake_Efficiency (%)'] < 70:
        issues.append('Brake wear / hydraulic issue')

    # 8️⃣ Suspension Health
    if row['Suspension_Health (%)'] < 75:
        issues.append('Suspension deterioration')

    # Combine all
    return 'Healthy' if len(issues) == 0 else ', '.join(issues)

synthetic['Predicted_Fault'] = synthetic.apply(predictive_maintenance, axis=1)

synthetic[['Vehicle_ID', 'Voltage (V)', 'Current (A)', 'Temperature (°C)',
           'Tire_Pressure (psi)', 'Oil_Level (%)', 'Vibration (g)',
           'Brake_Efficiency (%)', 'Suspension_Health (%)', 'Predicted_Fault']]

# Compute dataset-based limits
stats = synthetic.describe()

def dynamic_thresholds(col, low_factor=0.7, high_factor=1.3):
    """Return (low, high) dynamic thresholds from column stats."""
    mean = stats.loc['mean', col]
    return mean * low_factor, mean * high_factor

def dynamic_thresholds(col, low_factor=0.8, high_factor=1.2):
    """Return (low, high) dynamic thresholds from column stats."""
    mean = stats.loc['mean', col]
    return mean * low_factor, mean * high_factor

def predictive_maintenance(row):
    issues = []
    severity_score = 0

    # Battery/Circuit Fault
    v_low, v_high = dynamic_thresholds('Voltage (V)', 0.85, 1.15)
    if row['Voltage (V)'] < v_low or row['Voltage (V)'] > v_high:
        issues.append('Battery/Circuit Fault')
        severity_score += 2

    # Motor Overload
    c_low, c_high = dynamic_thresholds('Current (A)', 0.75, 1.25)
    if row['Current (A)'] > c_high:
        issues.append('Motor Overload')
        severity_score += 3

    # Engine / Oil Overheating
    t_low, t_high = dynamic_thresholds('Temperature (°C)', 0.9, 1.1)
    if row['Temperature (°C)'] > t_high:
        issues.append('Engine/Oil Overheating')
        severity_score += 4
    elif row['Temperature (°C)'] > t_low:
        issues.append('Slight Overheating')
        severity_score += 1

    # Tyre Pressure
    p_low, p_high = dynamic_thresholds('Tire_Pressure (psi)', 0.8, 1.3)
    if row['Tire_Pressure (psi)'] < p_low:
        issues.append('Low Tyre Pressure')
        severity_score += 2
    elif row['Tire_Pressure (psi)'] > p_high:
        issues.append('Overinflated Tyre')
        severity_score += 1

    # Oil Level
    o_low, _ = dynamic_thresholds('Oil_Level (%)', 0.8, 1.4)
    if row['Oil_Level (%)'] < o_low:
        issues.append('Low Oil Level')
        severity_score += 3

    # Chain/Clutch Imbalance (vibration)
    vib_low, vib_high = dynamic_thresholds('Vibration (g)', 0.7, 1.35)
    if row['Vibration (g)'] > vib_high:
        issues.append('Chain/Clutch Imbalance')
        severity_score += 2

    # Brake Fault
    b_low, _ = dynamic_thresholds('Brake_Efficiency (%)', 0.8, 1.0)
    if row['Brake_Efficiency (%)'] < b_low:
        issues.append('Brake Fault')
        severity_score += 3

    # Suspension Weakness
    s_low, _ = dynamic_thresholds('Suspension_Health (%)', 0.8, 1.0)
    if row['Suspension_Health (%)'] < s_low:
        issues.append('Suspension Weakness')
        severity_score += 2

    # Compute severity & health
    max_score = 20
    health_score = max(0, 100 - (severity_score / max_score) * 100)

    if severity_score == 0:
        severity = '🟢 Low (Healthy)'
    elif severity_score <= 4:
        severity = '🟡 Medium'
    else:
        severity = '🔴 High'

    issue_text = 'None (All systems normal)' if not issues else ', '.join(issues)
    return pd.Series({
        'Predicted_Faults': issue_text,
        'Severity_Level': severity,
        'Health_Score': round(health_score, 1)
    })

results = synthetic.apply(predictive_maintenance, axis=1)
final_output = pd.concat([synthetic['Vehicle_ID'], results], axis=1)
final_output

import matplotlib.pyplot as plt

# Count the number of each severity level
severity_counts = final_output['Severity_Level'].value_counts()

# Create a color map for each severity
colors = {
    '🟢 Low (Healthy)': '#4CAF50',
    '🟡 Medium': '#FFC107',
    '🔴 High': '#F44336'
}

plt.figure(figsize=(6, 6))
plt.pie(
    severity_counts,
    labels=severity_counts.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=[colors[label] for label in severity_counts.index],
    wedgeprops={'edgecolor': 'black'}
)
plt.title('🚗 Vehicle Health & Fault Severity Distribution', fontsize=14)
plt.show()

plt.figure(figsize=(10, 5))
plt.bar(final_output['Vehicle_ID'], final_output['Health_Score'], color='skyblue', edgecolor='black')
plt.axhline(75, color='orange', linestyle='--', label='Medium Risk')
plt.axhline(50, color='red', linestyle='--', label='High Risk')
plt.title('🚘 Vehicle Health Scores Based on Predictive Maintenance', fontsize=14)
plt.xlabel('Vehicle ID')
plt.ylabel('Health Score (%)')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Sort by severity
severity_order = {'🔴 High': 3, '🟡 Medium': 2, '🟢 Low (Healthy)': 1}
final_output['Severity_Rank'] = final_output['Severity_Level'].map(severity_order)
critical = final_output.sort_values(by='Severity_Rank', ascending=False).head(3)

print("🚨 Top 3 Critical Vehicles for Immediate Attention:\n")
display(critical[['Vehicle_ID', 'Predicted_Faults', 'Severity_Level', 'Health_Score']])

def send_alerts(df):
    print("\n💬 Customer Engagement Messages:\n")
    for _, row in df.iterrows():
        if 'High' in row['Severity_Level']:
            print(f"⚠️ Vehicle {row['Vehicle_ID']} detected {row['Predicted_Faults']}.")
            print(f"📞 Voice Agent: 'Dear owner, your vehicle shows critical issues. "
                  f"A service slot has been reserved for tomorrow 10 AM.'\n")
        elif 'Medium' in row['Severity_Level']:
            print(f"ℹ️ Vehicle {row['Vehicle_ID']}: {row['Predicted_Faults']}. "
                  f"Recommended service within 3 days.\n")
        else:
            print(f"✅ Vehicle {row['Vehicle_ID']}: No major issues detected.\n")

send_alerts(final_output)

import random

time_slots = ["Tomorrow 10 AM", "Tomorrow 2 PM", "Wednesday 11 AM", "Wednesday 4 PM"]
final_output['Service_Slot'] = final_output.apply(
    lambda x: random.choice(time_slots) if 'High' in x['Severity_Level'] else 'N/A', axis=1
)

display(final_output[['Vehicle_ID', 'Severity_Level', 'Service_Slot']])

from collections import Counter

# Extract all predicted faults
all_faults = ', '.join(final_output['Predicted_Faults']).split(', ')
fault_counts = Counter([f for f in all_faults if f != 'None (All systems normal)'])

# Display insights
print("\n🏭 Manufacturing Quality Insights (RCA/CAPA):\n")
for fault, count in fault_counts.most_common():
    print(f"⚙️ {fault}: occurred in {count} vehicles")

print("\n📊 Suggestion: Focus on top recurring issues to improve design and prevent future failures.")

import random

def send_alerts(df):
    print("\n💬 === Customer Engagement Agent: Predictive Maintenance Alerts ===\n")

    for _, row in df.iterrows():
        vehicle_id = row['Vehicle_ID']
        faults = row['Predicted_Faults']
        severity = row['Severity_Level']

        if 'High' in severity:
            print(f"🚨 ALERT: Vehicle {vehicle_id}")
            print(f"⚠️ Detected Critical Faults: {faults}")
            print(f"🤖 Chatbot: 'Hello! Our system detected serious issues in your vehicle. Immediate service is recommended.'")
            print(f"🗣️ Voice Agent: 'Dear customer, your vehicle shows critical faults. A service slot has been auto-booked for tomorrow at 10 AM.'")
            print("-" * 80)

        elif 'Medium' in severity:
            print(f"⚙️ NOTICE: Vehicle {vehicle_id}")
            print(f"🟡 Detected Moderate Faults: {faults}")
            print(f"🤖 Chatbot: 'Your vehicle may need maintenance soon. Would you like to schedule a checkup this week?'")
            print(f"🗣️ Voice Agent: 'Dear customer, a few parts need inspection. We suggest booking a service within 3 days.'")
            print("-" * 80)

        else:
            print(f"✅ Vehicle {vehicle_id} is in good condition.")
            print(f"🤖 Chatbot: 'Everything looks perfect! No service required currently.'")
            print(f"🗣️ Voice Agent: 'Your vehicle health is excellent. Have a safe drive!'")
            print("-" * 80)

send_alerts(final_output)

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

# Navigate to your project folder
# %cd /content/drive/MyDrive/Your_Project

# Initialize Git if not done already
!git init
!git remote add origin https://github.com/<your-username>/<your-repo>.git
!git add .
!git commit -m "EY Techathon 6.0 project update"
!git push -u origin main

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ColabDatasets
!git init

!git config --global user.name "DharanisriPalanisamy"
!git config --global user.email "dharanisripalanisamyy@gmail.com"

!git remote add origin https://github.com/<DharanisriPalanisamy>/<EY Techathon>.git

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ColabDatasets/NEV_fault_Dataset

!ls /content/drive/MyDrive

!git init
!git remote add origin https://github.com/DharanisriPalanisamy/EY_Techathon6_Project.git
!git config --global user.name "DharanisriPalanisamy"
!git config --global user.email "your_github_email@example.com"
!git add .
!git commit -m "Initial commit - EY Techathon 6.0 dataset upload"